### PR TITLE
style: :lipstick: update color palette

### PR DESCRIPTION
**Pull request by arihantbansal**
## Proposed changes (including videos or screenshots)
Updated color palette as per #48

## Issue(s)
#48 

## Further comments
More styling changes are needed. Unified color framework can be created with a later PR.

## Discord Details (!important)

Discord:papadarth#9317

### CODE REVIEW

**Comment by irffanasiff** [comment]
can you resolve the conflict @arihantbansal

**Comment by arihantbansal** [comment]
done

**Comment by arihantbansal** [comment]
@irffanasiff could you merge this?

**Comment by arihantbansal** [comment]
@irffanasiff could you reopen and merge this?

**Pull request closed without merging**
