### PR TITLE
Fix: Mobile UX

### PR DESCRIPTION
**Pull request by apoorvdwi**
## Proposed changes (including videos or screenshots)
- [x] Fixed the bug where tabs were auto-opening on mobile when scrolling
- [x] Swipeable tabs added
- [x] Updated .env.local.example to remove the /xp route from BACKEND_URL as it is already specified in the code to send request to `${process.env.BACKEND_URL}/xp`
- [x] Added env formatted in .vscode/settings.json 

## Issue(s)

#13 

## Discord Details (!important)

Discord:Apoorvdwi#9124

### CODE REVIEW

**Comment by irffanasiff** [comment]
@apoorvdwi  please resolve the conflicts

**Comment by apoorvdwi** [comment]
Merge conflicts fixed

**Comment by irffanasiff** [comment]
https://user-images.githubusercontent.com/74172466/208253559-41a44499-5df5-4964-b798-bc236fcd34a6.MP4

Hey @apoorvdwi can you look into this it works fine except the the part in the tab header which is hidden ( it would be better if you can make the tabs bar scroll too when that tab is active, i hope you understand what i am trying to say, it looks weird this way ) all other things are great

**Comment by apoorvdwi** [comment]
On it, doing that

**Comment by apoorvdwi** [comment]
Done, added the changes

**Pull request merged**
